### PR TITLE
IPA enable 4.1

### PR DESCRIPTION
**Pull request by Leo-Yan**
Enable IPA on Hikey, so when the thermal reach high level the SoC will consume sustainable power and stay at 960Mhz. So will have much better performance than previous governor.

### CODE REVIEW

**Comment by johnstultz-work** [comment]
Sorry, this is a dumb question, but:  Is there a simple way for me to test that this is all working on my builds?

**Comment by Leo-Yan** [comment]
Hi John,

On Mon, Jan 04, 2016 at 05:03:57PM -0800, John Stultz wrote:

> Sorry, this is a dumb question, but:  Is there a simple way for me to test that this is all working on my builds?

You could test with below script with dhry2 [1], after applied patches
the testing result will be much better than without these patches.

./run_dhry2_batch.sh

#!/bin/sh

/root/dhry2 300 &
/root/dhry2 300 &
/root/dhry2 300 &
/root/dhry2 300 &
/root/dhry2 300 &
/root/dhry2 300 &
/root/dhry2 300 &
/root/dhry2 300 &

[1] http://people.linaro.org/~leo.yan/binaries/dhry2

Thanks,
Leo Yan

**Comment by johnstultz-work** [comment]
Ok. That helps illustrate the issue and the fix. Thanks. Will merge this in a bit.

**Comment by Leo-Yan** [comment]
On Mon, Jan 04, 2016 at 09:03:45PM -0800, John Stultz wrote:

> Merged #170.

Thanks.

**Pull request merged**
