### PR TITLE
Android: Enable UHID for BT mouse functionality

### PR DESCRIPTION
**Pull request by vishalbhoj**

### CODE REVIEW

**Comment by vishalbhoj** [comment]
The config is already present in android-recommended.cfg but the kernel currently crashes if it is built with android-recommended.cfg hence I have just include UHID into android-base.cfg for now.

**Comment by fboudra** [comment]
there's changes unrelated to BT. Especially, we disable wifi.

**Comment by vishalbhoj** [comment]
Please ignore this request. Created a new pull request: https://github.com/96boards/linux/pull/72

**Comment by fboudra** [comment]
please ignore my comment. I see the arm64 defconfig wifi changes not merged. looks good.

**Pull request closed without merging**
