### PR TITLE
Tsensor: fix the tsenor driver and delete some dts property

### PR DESCRIPTION
**Pull request by kongzizaixian**
Signed-off-by: kongxinwei kong.kongxinwei@hisilicon.com

### CODE REVIEW

**Comment by kongzizaixian** [comment]
usleep_range replace of msleep function

**Comment by kongzizaixian** [comment]
usleep_range replace of msleep function

**Comment by kongzizaixian** [comment]
delete a return and fix some detail code about  define variable problem

**Comment by kongzizaixian** [comment]
delete a return and fix some detail code about define variable problem

**Comment by ldts** [comment]
fixed commit name.
run scripts/checkpatch.pl and scripts/cleanpatch.pl
merged.

**Pull request closed without merging**
