### PR TITLE
Mmc check

### PR DESCRIPTION
**Pull request by gaozhangfei**
mmc update

### CODE REVIEW

**Comment by ldts** [comment]
How many of these commits are actual bug fixes and what are the problems they are trying to fix? 
It seems we are going back and forth with the mmc clocks: can we make sure things are correct this time please?

**Comment by gaozhangfei** [comment]
This is prepartion for upstream with some optimization.

**Comment by ldts** [comment]
ah I see, this contains some of the driver modifications I did in the dw_mmc branch. Has this been tested enough? I did only some basic validation since the hisilicon driver seemed to be in a state of flux (so I have been pretty much waiting for it to stabilize a little).  

have you run enough testing?

**Comment by gaozhangfei** [comment]
Test only high speed mode, no uhs mode card.
It is better merge to see any issue.
In preparing on mmc-next.

**Comment by ldts** [comment]
sorry no, not this week (we are working towards a release on Friday). if you want this to be on the release I need you to at least test UHS (I remember I run speed tests back when I did some of the changes you are committing now but we need this checked again - I saw a drop from 14MB/s to 13.4MB/s). Otherwise this can wait.

**Comment by ldts** [comment]
hold on I might have a card around (I might be able to test this for you)

**Comment by gaozhangfei** [comment]
sure, thanks, it is not hurry.
I still met some problem about sd card in mmc-next, which has many dependence.

**Comment by ldts** [comment]
I tested this request and performance figures are the same compared to release 274. Let me know if you still want me to merge this. thanks.

**Comment by gaozhangfei** [comment]
Then it can be merged, thanks.
We can find issues as early as possible

**Comment by gaozhangfei** [comment]
Have submit another pull request since find one issue in mmc-next. 
Only update patch "drivers/clk: hi6220: add mmc reset clk"

**Pull request closed without merging**
