### PR TITLE
Enable PSCI for v3.18

### PR DESCRIPTION
**Pull request by Leo-Yan**
Enable PSCI for v3.18

### CODE REVIEW

**Comment by fboudra** [comment]
a regression is introduced with this change when using Hisilicon's bootloader.
The boot will hang. 2 workarounds are available:
- set "maxcpus=1" in kernel command line
- use another dtb with enable-method = "spin-table" instead of enable-method = "psci"

It has been proposed to provide a legacy dtb and use the PSCI enabled combination (UEFI + kernel) as the default since it is the long term plan

**Comment by koenkooi** [comment]
I can confirm this patch also works with UEFI+4.0rc3+dtb-from-3.18

**Comment by ldts** [comment]
Leo-yan, can you confirm that this is a conscious decision to stop users from using the hisilicon bootloader? are you aware of the implications?

**Comment by Leo-Yan** [comment]
We are planning to use ATF + UEFI, so this will replace hisilicon's bootloader; now we still are working on porting hisilicon's bootloader code to ATF/UEFI so that can meet the release requirement.

Like Fathi said, maybe we can provide a legacy dtb to compatiable w/t hisilicon's bootloader; so that we can support two kinds of bootloaders in short term.

BTW, regard of Jorge's question, it's better u can confirm w/t Scott/Usman/Haojian when is a good time point to remove hisilicon bootloader.

**Comment by ldts** [comment]
shouldn't we better have another hi6220.dtsi selectable at build time? there is work that might need device tree changes that could be carried out still using the hisilicon bootloader. Using precompiled dtbs might cause confusion.

**Comment by fboudra** [comment]
I'm more comfortable to ship a legacy dtb and document it. I assume we'll get rid of legacy as soon as we get rid of HiSilicon bootloader.

**Comment by ldts** [comment]
do you know when will that happen? besides, what would be the advantage? device trees live in the kernel and are built along with the kernel for a reason. Adding a commit that brings in a new build config is equally easy to remove and keeps all the info self contained in tree (without having to look for documents and binaries). in any case, if it makes the release process easier for you and we are talking of  a couple of weeks I guess we can go either way.

**Comment by ldts** [comment]
merged to hikey-psci branch to allow psci/ATF feature development.

**Comment by koenkooi** [comment]
reopening since it's not in the main branch yet.

**Comment by ldts** [comment]
please send the pull request to the hikey-psci topic branch. this cant be merged to hikey.

**Comment by koenkooi** [comment]
Why not? It is needed to have all cpus working with UEFI. Why are people so scared to make the call to have all cores working with UEFI and only one with that horrid, binary-only, closed-source evil vendor bootloader?

**Comment by ldts** [comment]
AFAIK not enough testing has been done: once UEFI offers the same functionality than the vendor's bootloader we will definitively make the move (that has always been the plan as you know and it is the direction that we are following). If what you are saying is that they are functionally equivalent now, then sure, lets discuss and move ahead. But I dont think this is the case.

**Comment by koenkooi** [comment]
It has more functionality at this point:
- you can store multiple bootentries
- it has a builtin editor for boot entries
- Fastboot support
- Builtin shell

And more.

**Comment by suihkulokki** [comment]
I agree with Koen that UEFI is mature enough now. 

> AFAIK not enough testing has been done
> And the move to PSCI/UEFI by default is the only way to get more testing.

IIRC The pcsi move will not even break booting with old bootloader - they will just have to live with one core. Which, if a problem for the user, is a good motivation to move to UEFI..

**Comment by fboudra** [comment]
beside having one core, there's still known issues on uefi:
- rootfs can't be flashed with UEFI reliably. It results in mount issues.
- SD card is still a work in progress and is considered not supported with UEFI

I'm not arguing agree/disagree. There's still things that other people consider a blocker at this point, even the developer working on it.

**Comment by koenkooi** [comment]
There needs to be an incentive to switch to UEFI so more people use it and give feedback/report bugs or even fix them.

Having clear requirements, meaning more detailed than just "feature parity" would go a long way.

Having said all that, the only drawback to this pull request is having only one core on the evil vendor bootloader, is that really such a big problem that prevents merging this right now? AFAICT the board will ship with UEFI, so we should be pushing that, not stick with the old and hope the new will be ready in time for launch.

**Comment by ldts** [comment]
No, the board will not ship with UEFI.

In any case please send the pull request to the topic branch - topic/hikey/psci tracks hikey: it is a matter of time until we push this to the main branch, I wouldn't worry too much about it at this point.

**Comment by koenkooi** [comment]
No support in mainline, not shipping with an open source bootloader, this hikey board is a farce.

**Comment by ldts** [comment]
Koen, it will get there - upstream - and UEFI will be available: many are working towards it. It just wont happen as fast as we would all like but such is life.

**Comment by fboudra** [comment]
close pull request in favor of https://github.com/96boards/linux/pull/97

**Pull request closed without merging**
