### PR TITLE
uart: hi6220: support high speed uart interface

### PR DESCRIPTION
**Pull request by william-wfei**
Some devices such like bluetooth need high speed uart,so add
switch function.

Signed-off-by: Fei Wang w.f@huawei.com

### CODE REVIEW

**Comment by koenkooi** [comment]
Isn't it a better idea to fix the clock driver to support reparenting instead of coming up with extra DT bindings?
If DT bindings are the only way to fix this, they need to be documented and reviewed at devicetree@vger.kernel.org.

**Comment by ldts** [comment]
yes I was discussing exactly this with the LT. As is, this commit won't be accepted upstream.

**Comment by william-wfei** [comment]
yes, this definitely will not be accepted by upstream community.Better solution would be to define directly a different clock as high frequency source. i thought we need to get a "can work" version so we do not block any other guys  who want to test BT at 3M and develop some feature for that, and then,we need to rewrite as community rule , rebase to top-tip kernel ,send patch to community ,talk with them and some times latter, our patch in mainline. it seems i was wrong. OK, i will talk about this issue to bintian who maintain hi6220 clk subsystem.

**Comment by ldts** [comment]
Will, we are still having this discussion internally and will communicate when agreed but in my view, to be accepted in this tree patches just need to be reasonable up to a level so the tree doesn't become un-maintainable (so there is no need to have the software upstreamed before it can land here). Also acceptance might depend on delivery times as we can create temporary branches for important features like this one - ie, how long do you think you need to define a high frequency clock source and so on.

**Comment by william-wfei** [comment]
I need double check with bintian, so tomorrow , i can feedback to you.

**Comment by ldts** [comment]
Thanks. In the meantime, please check if you can address the following issues:
1. clk-private.h doesnt exist upstream so avoid its usage.
2. the clock consumer must not be aware of the clock hierarchy: the hisi clock driver should support parent rate propagation via the CLK_SET_RATE_PARENT flag and clock re-parent via
   the .determine_rate callback.
3. avoid new DT settings

I believe a good option would be to assign the the UART clock from the device tree via standard assign-clock-\* tags. We should be able to upstream that change.

**Comment by ldts** [comment]
when could we see a follow up on this commit?

**Pull request closed without merging**
